#include <windows.h>
#include <tchar.h>
#include <stdlib.h>

struct win32msgid{
	const TCHAR* 	name;
	int				id;
};

#define ID_REG(x)	{_T(#x), x}

static struct win32msgid _id_reg[] = {
	ID_REG(WM_NULL),
	ID_REG(WM_CREATE),
	ID_REG(WM_DESTROY),
	ID_REG(WM_MOVE),
	ID_REG(WM_SIZE),
	ID_REG(WM_ACTIVATE),
	ID_REG(WM_SETFOCUS),
	ID_REG(WM_KILLFOCUS),
	ID_REG(WM_ENABLE),
	ID_REG(WM_SETREDRAW),
	ID_REG(WM_SETTEXT),
	ID_REG(WM_GETTEXT),
	ID_REG(WM_GETTEXTLENGTH),
	ID_REG(WM_PAINT),
	ID_REG(WM_CLOSE),
	ID_REG(WM_QUERYENDSESSION),
	ID_REG(WM_QUIT),
	ID_REG(WM_QUERYOPEN),
	ID_REG(WM_ERASEBKGND),
	ID_REG(WM_SYSCOLORCHANGE),
	ID_REG(WM_ENDSESSION),
	ID_REG(WM_QUERYENDSESSION),
	ID_REG(WM_SHOWWINDOW),
	ID_REG(WM_ACTIVATEAPP),
	ID_REG(WM_FONTCHANGE),
	ID_REG(WM_TIMECHANGE),
	ID_REG(WM_CANCELMODE),
	ID_REG(WM_SETCURSOR),
	ID_REG(WM_MOUSEACTIVATE),
	ID_REG(WM_CHILDACTIVATE),
	ID_REG(WM_QUEUESYNC),
	ID_REG(WM_GETMINMAXINFO),
	ID_REG(WM_PAINTICON),
	ID_REG(WM_ICONERASEBKGND),
	ID_REG(WM_NEXTDLGCTL),
	ID_REG(WM_SPOOLERSTATUS),
	ID_REG(WM_DRAWITEM),
	ID_REG(WM_MEASUREITEM),
	ID_REG(WM_DELETEITEM),
	ID_REG(WM_VKEYTOITEM),
	ID_REG(WM_KEYDOWN),
	ID_REG(WM_CHARTOITEM),
	ID_REG(WM_CHAR),
	ID_REG(WM_SETFONT),
	ID_REG(WM_GETFONT),
	ID_REG(WM_SETHOTKEY),
	ID_REG(WM_GETHOTKEY),
	ID_REG(WM_QUERYDRAGICON),
	ID_REG(WM_COMPAREITEM),
	ID_REG(WM_COMPACTING),
	ID_REG(WM_WINDOWPOSCHANGING),
	ID_REG(WM_WINDOWPOSCHANGED),
	ID_REG(WM_POWER),
	ID_REG(WM_COPYDATA),
	ID_REG(WM_CANCELJOURNAL),
	ID_REG(WM_NOTIFY),
	ID_REG(WM_INPUTLANGCHANGEREQUEST),
	ID_REG(WM_INPUTLANGCHANGE),
	ID_REG(WM_TCARD),
	ID_REG(WM_HELP),
	ID_REG(WM_USERCHANGED),
	ID_REG(WM_NOTIFYFORMAT),
	ID_REG(WM_NOTIFY),
	ID_REG(WM_CONTEXTMENU),
	ID_REG(WM_STYLECHANGING),
	ID_REG(WM_STYLECHANGED),
	ID_REG(WM_DISPLAYCHANGE),
	ID_REG(WM_GETICON),
	ID_REG(WM_SETICON),
	ID_REG(WM_NCCREATE),
	ID_REG(WM_CREATE),
	ID_REG(WM_NCDESTROY),
	ID_REG(WM_NCCALCSIZE),
	ID_REG(WM_NCHITTEST),
	ID_REG(WM_NCPAINT),
	ID_REG(WM_NCACTIVATE),
	ID_REG(WM_NCMOUSEMOVE),
	ID_REG(WM_NCLBUTTONDOWN),
	ID_REG(WM_NCLBUTTONUP),
	ID_REG(WM_NCLBUTTONDBLCLK),
	ID_REG(WM_NCRBUTTONDOWN),
	ID_REG(WM_NCRBUTTONUP),
	ID_REG(WM_NCRBUTTONDBLCLK),
	ID_REG(WM_NCMBUTTONDOWN),
	ID_REG(WM_NCMBUTTONUP),
	ID_REG(WM_NCMBUTTONDBLCLK),
	ID_REG(WM_KEYDOWN),
	ID_REG(WM_KEYUP),
	ID_REG(WM_CHAR),
	ID_REG(WM_KEYDOWN),
	ID_REG(WM_DEADCHAR),
	ID_REG(WM_KEYUP),
	ID_REG(WM_SYSKEYDOWN),
	ID_REG(WM_SYSKEYUP),
	ID_REG(WM_SYSCHAR),
	ID_REG(WM_SYSKEYDOWN),
	ID_REG(WM_SYSDEADCHAR),
	ID_REG(WM_SYSKEYUP),
	ID_REG(WM_INITDIALOG),
	ID_REG(WM_COMMAND),
	ID_REG(WM_SYSCOMMAND),
	ID_REG(WM_TIMER),
	ID_REG(WM_HSCROLL),
	ID_REG(WM_VSCROLL),
	ID_REG(WM_INITMENU),
	ID_REG(WM_INITMENUPOPUP),
	ID_REG(WM_MENUSELECT),
	ID_REG(WM_MENUCHAR),
	ID_REG(WM_ENTERIDLE),
	ID_REG(WM_MENURBUTTONUP),
	ID_REG(WM_MENUDRAG),
	ID_REG(WM_MENUGETOBJECT),
	ID_REG(WM_UNINITMENUPOPUP),
	ID_REG(WM_MENUCOMMAND),
	ID_REG(WM_CHANGEUISTATE),
	ID_REG(WM_UPDATEUISTATE),
	ID_REG(WM_QUERYUISTATE),
	ID_REG(WM_CTLCOLORMSGBOX),
	ID_REG(WM_CTLCOLOREDIT),
	ID_REG(WM_CTLCOLORLISTBOX),
	ID_REG(WM_CTLCOLORBTN),
	ID_REG(WM_CTLCOLORDLG),
	ID_REG(WM_CTLCOLORSCROLLBAR),
	ID_REG(WM_CTLCOLORSTATIC),
	ID_REG(WM_MOUSEMOVE),
	ID_REG(WM_LBUTTONDOWN),
	ID_REG(WM_LBUTTONUP),
	ID_REG(WM_LBUTTONDBLCLK),
	ID_REG(WM_RBUTTONDOWN),
	ID_REG(WM_RBUTTONUP),
	ID_REG(WM_RBUTTONDBLCLK),
	ID_REG(WM_MBUTTONDOWN),
	ID_REG(WM_MBUTTONUP),
	ID_REG(WM_MBUTTONDBLCLK),
	ID_REG(WM_MOUSEWHEEL),
	ID_REG(WM_PARENTNOTIFY),
	ID_REG(WM_ENTERMENULOOP),
	ID_REG(WM_EXITMENULOOP),
	ID_REG(WM_SIZING),
	ID_REG(WM_CAPTURECHANGED),
	ID_REG(WM_MOVING),
	ID_REG(WM_POWERBROADCAST),
	ID_REG(WM_DEVICECHANGE),
	ID_REG(WM_MDICREATE),
	ID_REG(WM_MDIDESTROY),
	ID_REG(WM_MDIACTIVATE),
	ID_REG(WM_MDIRESTORE),
	ID_REG(WM_MDINEXT),
	ID_REG(WM_MDIMAXIMIZE),
	ID_REG(WM_MDITILE),
	ID_REG(WM_MDICASCADE),
	ID_REG(WM_MDIICONARRANGE),
	ID_REG(WM_MDIGETACTIVE),
	ID_REG(WM_MDISETMENU),
	ID_REG(WM_ENTERSIZEMOVE),
	ID_REG(WM_EXITSIZEMOVE),
	ID_REG(WM_DROPFILES),
	ID_REG(WM_MDIREFRESHMENU),
	ID_REG(WM_MOUSEHOVER),
	ID_REG(WM_MOUSELEAVE),
	ID_REG(WM_CUT),
	ID_REG(WM_COPY),
	ID_REG(WM_PASTE),
	ID_REG(WM_CLEAR),
	ID_REG(WM_UNDO),
	ID_REG(WM_DESTROYCLIPBOARD),
	ID_REG(WM_DRAWCLIPBOARD),
	ID_REG(WM_PAINTCLIPBOARD),
	ID_REG(WM_VSCROLLCLIPBOARD),
	ID_REG(WM_SIZECLIPBOARD),
	ID_REG(WM_ASKCBFORMATNAME),
	ID_REG(WM_CHANGECBCHAIN),
	ID_REG(WM_HSCROLLCLIPBOARD),
	ID_REG(WM_QUERYNEWPALETTE),
	ID_REG(WM_PALETTEISCHANGING),
	ID_REG(WM_PALETTECHANGED),
	ID_REG(WM_HOTKEY),
	ID_REG(WM_PRINT),
	ID_REG(WM_PRINTCLIENT),
	ID_REG(WM_APP),
	ID_REG(WM_USER)
};

static int _id_reg_init = 0;

int msg_id_cmp(const void* left, const void* right){
	struct win32msgid* pl = (struct win32msgid*)left;
	struct win32msgid* pr = (struct win32msgid*)right;
	
	return pl->id - pr->id;
}

static void win32_msg_id_init()
{
	if (_id_reg_init)
		return;
		
	qsort(_id_reg, 
		  sizeof(_id_reg)/sizeof(_id_reg[0]), 
		  sizeof(_id_reg[0]),
		  msg_id_cmp);
}

const TCHAR* win32_msg_id(int id)
{
	int left = 0, right = sizeof(_id_reg)/sizeof(_id_reg[0]);
	int middle;
	
	win32_msg_id_init();
	
	while(left < right){
		middle = left + (right - left)/2;
		if (id < _id_reg[middle].id)
			right = middle;
		else if (id > _id_reg[middle].id)
			left = middle+1;
		else
			return _id_reg[middle].name;
	}
	
	return _T("UNKNOW");
}